services:
  devbox-healthcheck:
    image: curlimages/curl
    entrypoint: /bin/sleep 10000
    links:
      - devbox
    depends_on:
      - devbox
    healthcheck:
      test: curl --fail http://devbox:8888/__healthcheck || exit 1
      interval: 1s
      timeout: 20s
      retries: 100
  scheduling-app-healthcheck:
    image: curlimages/curl
    entrypoint: /bin/sleep 10000
    links:
      - devbox
    depends_on:
      - scheduling-app
    healthcheck:
      test: curl --fail http://devbox:8888/scheduling-app-healthcheck || exit 1
      interval: 1s
      timeout: 20s
      retries: 100
  scheduling-app:
    build:
      context: .
      dockerfile: Dockerfile.scheduling-node-app.dev
    depends_on:
      devbox-healthcheck:
        condition: service_healthy
    links:
      - devbox
    environment:
      APP_ID: scheduling
      APP_SECRET: secret
      APP_URL: http://scheduling-app:8091/
      APP_PORT: 8091
    env_file:
      - .env.devbox
    volumes:
      - .:/app
    tty: true
  devbox:
    image: healthsamurai/aidboxone:latest
    depends_on:
      - devbox-db
    links:
      - devbox-db:database
    ports:
      - 8888:8888
    env_file:
      - .env.devbox
    environment:
      - AIDBOX_LICENSE
  devbox-db:
    image: healthsamurai/aidboxdb:14.5
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devbox
