services:
  devbox-healthcheck:
    image: curlimages/curl
    entrypoint: /bin/sleep 10000
    links:
      - devbox
    depends_on:
      - devbox
    healthcheck:
      test: curl --fail ${AIDBOX_URL}/__healthcheck || exit 1
      interval: 1s
      timeout: 20s
      retries: 100
  scheduling-app-healthcheck:
    image: curlimages/curl
    entrypoint: /bin/sleep 10000
    links:
      - devbox
    depends_on:
      - scheduling-app
    healthcheck:
      test: curl --fail ${AIDBOX_URL}/scheduling-app-healthcheck || exit 1
      interval: 1s
      timeout: 20s
      retries: 100
  scheduling-app:
    build:
      context: .
      dockerfile: Dockerfile.scheduling-node-app.dev
    depends_on:
      devbox-healthcheck:
        condition: service_healthy
    links:
      - devbox
    environment:
      APP_ID: scheduling
      APP_SECRET: secret
      APP_URL: http://scheduling-app:8091/
      APP_PORT: 8091
    volumes:
      - .:/app
    tty: true
  devbox:
    image: ${AIDBOX_IMAGE}
    depends_on:
      - devbox-db
    links:
      - devbox-db:database
    ports:
      - ${AIDBOX_PORT}:${AIDBOX_PORT}
    env_file:
      - .env.devbox
    environment:
      - AIDBOX_LICENSE
      - PGHOST=database
  devbox-db:
    image: ${PGIMAGE}
    ports:
      - ${PGHOSTPORT}:${PGPORT}
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
